[package]
name    = "auth"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow       = { workspace = true }
argon2       = { workspace = true }
axum         = { workspace = true }
axum-extra   = { workspace = true }
chrono       = { workspace = true }
jsonwebtoken = { workspace = true }
serde        = { workspace = true }
serde_json   = { workspace = true }
thiserror    = { workspace = true }
tokio        = { workspace = true }
tracing      = { workspace = true }
uuid         = { workspace = true }

db = { path = "../db" }
