[package]
name    = "api"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "apex-api"
path = "src/main.rs"

[dependencies]
anyhow       = { workspace = true }
axum         = { workspace = true }
axum-extra   = { workspace = true }
base64       = { workspace = true }
bytes        = { workspace = true }
chrono       = { workspace = true }
dotenvy      = { workspace = true }
futures      = { workspace = true }
futures-util = { workspace = true }
hyper        = { workspace = true }
jsonwebtoken = { workspace = true }
prometheus   = { workspace = true }
reqwest      = { workspace = true }
serde        = { workspace = true }
serde_json   = { workspace = true }
thiserror    = { workspace = true }
tokio        = { workspace = true }
tokio-util   = { workspace = true }
tower        = { workspace = true }
tower-http   = { workspace = true }
tracing      = { workspace = true }
tracing-subscriber = { workspace = true }
uuid         = { workspace = true }
validator    = { workspace = true }
bs58         = { workspace = true }
sqlx         = { workspace = true }

auth   = { path = "../auth" }
cache  = { path = "../cache" }
common = { path = "../common" }
db     = { path = "../db" }
flash-loans = { path = "../flash-loans" }
